@startuml Co2 Monitor Class Diagram
class "main.c" as MainC {

}

class app_main {

}
namespace App {
    class DisplayHandler {
        - DisplayScreenBase* currentScreen
        + void setScreen(DisplayScreenBase* newScreen)
        + void update()
    }
    class TouchHandler {

    }
    class SensorHandler {

    }
}

namespace UI {

    Interface DisplayScreenBase <<interface>>{
        + {abstract} void init()
        + {abstract} void update()
        + {abstract} void destroy()
    }
    
    class Bootscreen {

    }
    class Homescreen {

    }
    class SettingsScreen {

    }
}

namespace Drivers {

    interface DisplayDriverBase <<interface>>{
        + {abstract} void lvglDisplayInit()
    }

    interface TouchDriverBase <<interface>>{

    }

    interface SensorDriverBase <<interface>>{
        + {abstract} void init()
        + {abstract} void read()
        + {abstract} const osMessageQueueId_t getQueueHandle()
    }

    namespace SPI {
        class ST7796 {

        }
    }
    namespace I2C {
        class FT6336U {

        }

        class SCD40 {

        }
    }
}


' This syntax means Circle implements Shape
MainC --> app_main
app_main --> DisplayHandler
app_main --> TouchHandler
app_main --> SensorHandler

DisplayHandler --> DisplayDriverBase
DisplayHandler o-- DisplayScreenBase
DisplayScreenBase <|-- Homescreen
DisplayScreenBase <|-- SettingsScreen
DisplayScreenBase <|-- Bootscreen
TouchHandler --> TouchDriverBase
SensorHandler --> SensorDriverBase

DisplayDriverBase <|-- ST7796
TouchDriverBase <|-- FT6336U
SensorDriverBase <|-- SCD40
@enduml